name: Build Custom Database

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_db:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Custom Database for MiSTer Downloader
        uses: diegofigs/MiSTer-build-db@v1
        with:
          db-name: "remote_game_gallery"
