name: CI

on:
  pull_request:
  push:
    branches: [main]

env:
  appRoot: .github/app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.appRoot }}
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.appRoot }}/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm build
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.appRoot }}
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.15.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.appRoot }}/pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm lint
